### ISSUE TITLE
android: envoy mobile fails on api 21

### ISSUE THREAD

**Issue by buildbreaker** [lyft/envoy-mobile#608]
Error using API 21:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libenvoy_jni.so"...
 at java.lang.Runtime.loadLibrary(Runtime.java:371)
 at java.lang.System.loadLibrary(System.java:989)
 at io.envoyproxy.envoymobile.engine.JniLibrary$JavaLoader.<init>(JniLibrary.java:38)
 at io.envoyproxy.envoymobile.engine.JniLibrary$JavaLoader.<init>(JniLibrary.java:36)
 at io.envoyproxy.envoymobile.engine.JniLibrary.load(JniLibrary.java:29)
 at io.envoyproxy.envoymobile.engine.EnvoyEngineImpl.<init>(EnvoyEngineImpl.java:10)
 at io.envoyproxy.envoymobile.engine.AndroidEngineImpl.<init>(AndroidEngineImpl.java:8)
 at io.envoyproxy.envoymobile.AndroidEnvoyClientBuilder$1.invoke(AndroidEnvoyClientBuilder.kt:12)
 at io.envoyproxy.envoymobile.AndroidEnvoyClientBuilder$1.invoke(AndroidEnvoyClientBuilder.kt:6)
 at io.envoyproxy.envoymobile.EnvoyClientBuilder.build(EnvoyClientBuilder.kt:74)
```

**Comment by buildbreaker** [comment]
https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#available-in-api-level-23

**Comment by buildbreaker** [comment]
Relates to: https://github.com/lyft/envoy-mobile/issues/726
