### ISSUE TITLE
android: ensure we can capture crashes and unhandled exceptions

### ISSUE THREAD

**Issue by goaway** [lyft/envoy-mobile#660]
There are a couple cases where current tooling cannot effectively capture what's happened when something goes wrong in Envoy Mobile.

- If a callback throws an uncaught exception, currently we swallow it silently in the JNI, rather than surfacing it, along with the stack, and causing the process to exit.
- If Envoy exits unexpectedly we have no way to signal this to the app (this is true for iOS as well).

Additionally, we need to investigate options and best practices for when NDK code (Envoy itself) simply crashes, so that tooling may still capture state.

**Comment by buildbreaker** [comment]
I was able to verify that if we have an exception thrown in the handlers, we do surface that stacktrace in the Android

What I did was I threw a new `Exception` with a specific message: `~~~ error occurred` and was able to see this message along with a stack trace in the logs:
```
03-10 13:34:18.167 7142-7483/com.example.app E/AndroidRuntime: FATAL EXCEPTION: pool-20-thread-1
    Process: com.lyft.android.driver.dev, PID: 7142
    java.lang.Error: java.lang.Exception: ~~~ error occurred
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Exception: ~~~ error occurred
        at io.envoyproxy.envoymobile.ResponseHandler$EnvoyHTTPCallbacksAdapter.onHeaders(ResponseHandler.kt:29)
        at io.envoyproxy.envoymobile.engine.JvmCallbackContext$1.run(JvmCallbackContext.java:93)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by rebello95** [comment]
Nice. We should be able to close this out then @buildbreaker?

**Comment by buildbreaker** [comment]
Closing since the second issue is not associated with Android
